 import = [
    "~/.config/alacritty/coolnight.toml"
]
#
#import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   # "~/.config/alacritty/catppuccin-mocha.toml"
#]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 1
blur = false 
[window.padding]
x = 20
y = 20

[font]
size = 12.0
offset.y = 6

[font.normal]
family = "MesloLGS Nerd Font Mono"
# style = "Regular"
#
# family = "FiraCode Nerd Font"
# style = "Light"

# TokyoNight Alacritty Colors
# Default colors

[keyboard]
bindings = [
#	{key = "Space", mods = "Control", chars = "\u0000"},
]


